-- PostgreSQL

-- 1) books.publication_status 用（integerで管理）
-- 0 = UNPUBLISHED, 1 = PUBLISHED
CREATE TABLE books (
                       book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title  TEXT   NOT NULL,
                       price  INTEGER NOT NULL CHECK (price >= 0),
                       publication_status INTEGER NOT NULL CHECK (publication_status IN (0, 1))
);

CREATE TABLE authors (
                         author_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name      TEXT NOT NULL,
                         birth_date DATE CHECK (birth_date <= CURRENT_DATE)
);

-- 著者と書籍の紐づけ（複合PK）
CREATE TABLE book_author_relations (
                                       book_id   BIGINT NOT NULL,
                                       author_id BIGINT NOT NULL,
                                       PRIMARY KEY (book_id, author_id),
                                       CONSTRAINT fk_bar_book
                                           FOREIGN KEY (book_id) REFERENCES books(book_id)
                                               ON DELETE CASCADE,
                                       CONSTRAINT fk_bar_author
                                           FOREIGN KEY (author_id) REFERENCES authors(author_id)
                                               ON DELETE RESTRICT
);

-- 著者に紐づく本を取得する用
CREATE INDEX idx_book_author_relations_author_id
    ON book_author_relations(author_id);
